version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /.jpg
  static_dir: images
- url: /.*
  script: AssignmentPortal.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest